name: Comprobar Tokens

on: [push]

jobs:
  comprobar-tokens:
    runs-on: self-hosted
    steps:
      - name: Comparar DEV_TOKEN contra LOCAL_DEV_TOKEN
        env:
          SECRET_DEV: ${{ secrets.DEV_TOKEN }}
        shell: pwsh
        run: |
          if ($env:SECRET_DEV -eq $env:LOCAL_DEV_TOKEN) {
            Write-Output "¡Exito! Los tokens coinciden."
            exit 0
          } else {
            Write-Output "Error: El secret y la variable local son distintos."
            exit 1
          }